const ShopActionTypes = {
    CHANGE_SELECTED_CATEGORY: 'CHANGE_SELECTED_CATEGORY',
    CHANGE_SELECTED_PRODUCT: 'CHANGE_SELECTED_PRODUCT',
    FETCH_PRODUCT_DATA_START: 'FETCH_PRODUCT_DATA_START',
    FETCH_PRODUCT_DATA_SUCCESS: 'FETCH_PRODUCT_DATA_SUCCESS',
    FETCH_PRODUCT_DATA_FAILURE: 'FETCH_PRODUCT_DATA_FAILURE'
}

export default ShopActionTypes