const CartActionTypes = {
    TOGGLE_CART_OVERLAY: 'TOGGLE_CART_OVERLAY',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    INCREMENT_ITEM: 'INCREMENT_ITEM',
    DECREMENT_ITEM: 'DECREMENT_ITEM'
}

export default CartActionTypes