const CurrencyActionTypes = {
    TOGGLE_CURRENCY_OVERLAY: 'TOGGLE_CURRENCY_OVERLAY',
    CHANGE_SELECTED_CURRENCY: 'CHANGE_SELECTED_CURRENCY',
    CHANGE_SELECTED_CURRENCY_SUCCESS: 'CHANGE_SELECTED_CURRENCY_SUCCESS',
    FETCH_CURRENCIES_START: 'FETCH_CURRENCIES_START',
    FETCH_CURRENCIES_SUCCESS: 'FETCH_CURRENCIES_SUCCESS',
    FETCH_CURRENCIES_FAILURE: 'FETCH_CURRENCIES_FAILURE'
}

export default CurrencyActionTypes